# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prof_pic',
            field=models.ImageField(default='Whiteboard/default-avatar.png', upload_to='./storage/'),
        ),
    ]
