# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170520_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prof_pic',
            field=models.ImageField(default='storage/default-avatar.png', upload_to='./storage/'),
        ),
    ]
