# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_auto_20170520_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
