# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_note_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(null=True, upload_to='./storage/'),
        ),
    ]
